### PR TITLE
API Integration & Update UI

### PR DESCRIPTION
**Pull request by andistevenli**
@yusmnn 
@GrimsAlphaDev 
@archndrx 
@rnwxyz 

Link Trello : https://trello.com/c/9HZKSesO

Preview Hasil:

https://github.com/Kelompok-4-Capstone-Alterra/flutter_women_center/assets/122267530/59579620-fb58-4491-99cf-f67066387673

API Integration Done:
- GET /users/reading-lists
- GET /users/reading-lists/:id
- POST /users/reading-lists
- PUT /users/reading-lists/:id
- DELETE /users/reading-lists/:id
- DELETE /users/reading-lists/save/:id

New UI:
- Widget Loading

Update:
- Custom Bottom Sheet Builder
- Search Text Box
- Detail Reading List Screen
- Saved Screen
- Article List Popup Menu Button
- Horizontal Article Card
- Reading List Sort by Bottom Sheet Content
- Saved Card
- Vertical Article Card

Deleted UI:
- Article Screen

Next API Integration:
- Counseling Rate & Review
- Counseling Link

### CODE REVIEW

**Review by archndrx — APPROVED** [review]
nais

**Review by yusmnn — APPROVED** [review]

**Comment by andistevenli** [comment]
Oh ya guys, untuk artikel nya masih kosong yah karena blm ada yg disave

**Comment by archndrx** [comment]
> Oh ya guys, untuk artikel nya masih kosong yah karena blm ada yg disave

oiya itu di model reading ada article model kepake kah ?

**Comment by andistevenli** [comment]
Kepake hanya utk nampilin di halaman detail reading list

**Review by rnwxyz — APPROVED** [review]

**Review by GrimsAlphaDev — APPROVED** [review]

**Pull request merged**
